// app/(protected)/dashboard/prd/page.tsx
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { getActiveOrganization } from '@/lib/session'
import { getAllPrds, deletePrd } from '@/features/prd/actions'
import { Button } from '@/components/ui/button'
import { FileText, ArrowRight, Trash2, CheckCircle2, Clock, Sparkles } from 'lucide-react'

export const dynamic = 'force-dynamic'

export default async function PrdsPage() {
  const org = await getActiveOrganization()
  if (!org) notFound()

  const prds = await getAllPrds()

  return (
    <div className="p-8 max-w-6xl mx-auto space-y-8">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-border pb-6">
        <div>
          <h1 className="text-2xl font-bold tracking-tight flex items-center gap-2.5">
            <FileText className="h-6 w-6 text-primary" />
            PRD Editor
          </h1>
          <p className="text-sm text-muted-foreground mt-1">
            Review, edit, and approve Product Requirement Documents generated by AI.
          </p>
        </div>
        <Link href="/dashboard/feature-requests">
          <Button variant="outline" className="gap-2">
            <Sparkles className="h-4 w-4 text-indigo-400" />
            New Feature Request
          </Button>
        </Link>
      </div>

      {/* PRD List */}
      {prds.length === 0 ? (
        <div className="rounded-xl border border-dashed border-border p-12 text-center space-y-4 bg-muted/10">
          <div className="mx-auto w-12 h-12 rounded-full bg-primary/10 flex items-center justify-center text-primary">
            <FileText className="h-6 w-6" />
          </div>
          <div className="space-y-1">
            <h3 className="font-semibold text-lg">No PRDs generated yet</h3>
            <p className="text-sm text-muted-foreground max-w-md mx-auto">
              Create a feature request to clarify requirements and generate your first Product Requirement Document.
            </p>
          </div>
          <Link href="/dashboard/feature-requests">
            <Button className="mt-2">Create Feature Request</Button>
          </Link>
        </div>
      ) : (
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          {prds.map((prd) => (
            <div
              key={prd.id}
              className="group relative flex flex-col justify-between rounded-xl border border-border bg-card p-6 shadow-sm transition-all hover:border-primary/50 hover:shadow-md"
            >
              <div className="space-y-3">
                <div className="flex items-center justify-between gap-2">
                  <span
                    className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-0.5 text-xs font-medium border ${
                      prd.status === 'APPROVED'
                        ? 'border-emerald-500/30 bg-emerald-500/10 text-emerald-400'
                        : 'border-amber-500/30 bg-amber-500/10 text-amber-400'
                    }`}
                  >
                    {prd.status === 'APPROVED' ? (
                      <>
                        <CheckCircle2 className="h-3 w-3" /> Approved
                      </>
                    ) : (
                      <>
                        <Clock className="h-3 w-3" /> Draft
                      </>
                    )}
                  </span>
                  <form
                    action={async () => {
                      'use server'
                      await deletePrd(prd.id)
                    }}
                  >
                    <button
                      type="submit"
                      title="Delete PRD"
                      className="text-muted-foreground hover:text-destructive transition-colors p-1 rounded-md hover:bg-muted"
                    >
                      <Trash2 className="h-4 w-4" />
                    </button>
                  </form>
                </div>

                <div>
                  <h2 className="font-semibold text-lg group-hover:text-primary transition-colors line-clamp-1">
                    {prd.featureRequest.title}
                  </h2>
                  <p className="text-sm text-muted-foreground line-clamp-3 mt-1.5">
                    {prd.problemStatement || prd.featureRequest.description}
                  </p>
                </div>
              </div>

              <div className="pt-6 mt-4 border-t border-border/50 flex items-center justify-between text-xs text-muted-foreground">
                <span>
                  {new Date(prd.createdAt).toLocaleDateString('en-US', {
                    month: 'short',
                    day: 'numeric',
                    year: 'numeric',
                  })}
                </span>
                <Link
                  href={`/dashboard/prd/${prd.id}`}
                  className="inline-flex items-center gap-1 font-medium text-primary hover:underline"
                >
                  Edit PRD <ArrowRight className="h-3.5 w-3.5" />
                </Link>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
